// <auto-generated />
using System;
using AmitWebAppMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AmitWebAppMVC.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20230123042947_initials")]
    partial class initials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AmitWebAppMVC.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(8);

                    b.Property<int?>("Department")
                        .HasColumnType("int")
                        .HasColumnOrder(7);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("date")
                        .HasColumnOrder(4);

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<int>("RecStatus")
                        .HasColumnType("int")
                        .HasColumnOrder(10);

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("UpdateOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9);

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddOn = new DateTime(2023, 1, 23, 9, 59, 47, 471, DateTimeKind.Local).AddTicks(6946),
                            Department = 1,
                            Email = "amit.sircltech@.com",
                            HireDate = new DateTime(2023, 1, 23, 9, 59, 47, 471, DateTimeKind.Local).AddTicks(6975),
                            Job = "Programmer",
                            Name = "Amit",
                            RecStatus = 1,
                            Salary = 50000m,
                            UpdateOn = new DateTime(2023, 1, 23, 9, 59, 47, 471, DateTimeKind.Local).AddTicks(6963)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
